image: golang:1.14
stages:
  - init
  - test & build
  - release
  - package
  - publish

init:
  stage: init
  image: usvc/ci:go-dependencies
  cache:
    key: ${CI_COMMIT_REF_NAME}
    paths: ["./vendor"]
  artifacts:
    paths: ["./vendor"]
  script: ["entrypoint"]

unit test:
  stage: test & build
  image: usvc/ci:go-test
  dependencies: ["init"]
  artifacts:
    paths: ["./c.out"]
  script: ["entrypoint"]

.build:
  image: usvc/ci:go-build-production
  stage: test & build
  dependencies: ["init"]
  artifacts:
    paths: ["./bin/*"]
  variables:
    BIN_NAME: db
  before_script: ["git fetch"]
  script: ["entrypoint"]
build_linux:
  extends: .build
  variables:
    GOOS: linux
    GOARCH: amd64
build_macos:
  extends: .build
  variables:
    GOOS: darwin
    GOARCH: amd64
build_windows:
  extends: .build
  variables:
    GOOS: windows
    GOARCH: "386"

version bump:
  stage: release
  only: ["master"]
  image: usvc/ci:version-bump-gitlab
  script: ["entrypoint"]

coverage report:
  allow_failure: true
  stage: release
  dependencies: ["unit test"]
  image: usvc/ci:go-coverage-code-climate
  script: ["entrypoint"]

.compress:
  allow_failure: true
  image: usvc/ci:compress
  stage: package
  script: ["entrypoint"]
  artifacts:
    paths: ["./bin/*"]
compress linux:
  extends: .compress
  dependencies: ["build linux"]
  variables:
    BIN_SRC: db_linux_amd64
compress macos:
  extends: .compress
  dependencies: ["build macos"]
  variables:
    BIN_SRC: db_darwin_amd64
compress_windows:
  extends: .compress
  dependencies: ["build windows"]
  variables:
    BIN_EXT: .exe
    BIN_SRC: db_windows_386

dockerize:
  stage: package
  only: ["tags"]
  services: ["docker:19.03.1-dind"]
  image: usvc/ci:docker-build
  artifacts:
    paths: ["./build/*"]
  variables:
    DOCKER_IMAGE_URL: usvc/db
  script: ["entrypoint"]

dockerhub:
  stage: publish
  only: ["tags"]
  services: ["docker:19.03.1-dind"]
  image: usvc/ci:docker-publish
  dependencies: ["dockerize"]
  variables:
    DOCKER_IMAGE_URL: usvc/db
  script: ["entrypoint"]
