CREATE TABLE `accounts` (
  id INTEGER UNSIGNED PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
  name VARCHAR(256) NOT NULL,
  email VARCHAR(256) UNIQUE NOT NULL,
  password BINARY NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
) Engine=InnoDB;
